name: Fetch Flight Data

on:
  schedule:
  - cron: "0 7 * * *" # every day at 7 AM
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    env:
      GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
      AMADEUS_SECRET: ${{ secrets.AMADEUS_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flight script
      run: python main.py

    - name: Commit and push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add flight_price_history.csv
        git diff --cached --quiet || git commit -m "Update flight data [auto]"
        git push
